# Generated by Django 4.0.6 on 2022-07-11 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'verbose_name': 'Еда', 'verbose_name_plural': 'Еда'},
        ),
    ]
